version: '3.9'

services:
  suffixtree:
    image: suffixtree
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./:/app/
    ports:
      - 5000:5000
    environment: 
      PORT: 5000
      FLASK_DEBUG: 1
      FLASK_APP: app.py
      FLASK_ENV: development
      